var Crafty = require('./core');
require('./2D');
require('./animation');
require('./canvas');
require('./collision');
require('./color');
require('./controls');
require('./DebugLayer');
require('./device');
require('./diamondiso');
require('./DOM');
require('./drawing');
require('./extensions');
require('./HashMap');
require('./html');
require('./import');
require('./isometric');
require('./keycodes');
require('./loader');
require('./math');
require('./model');
require('./particles');
require('./scenes');
require('./sound');
require('./sprite-animation');
require('./sprite');
require('./storage');
require('./text');
require('./time');
require('./version');
require('./viewport');

window.Crafty = Crafty;